-- Skema Tabel untuk PostgreSQL di Supabase

-- 1. Membuat tabel 'materials' untuk Pengadaan Bahan Baku (MM)
CREATE TABLE IF NOT EXISTS public.materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL, -- Kolom untuk isolasi data tiap pengguna
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    qty NUMERIC NOT NULL,
    entry_date DATE NOT NULL,
    exp_date DATE NOT NULL,
    cost NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Membuat tabel 'sales' untuk Pesanan Penjualan (SD)
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL, -- Kolom untuk isolasi data tiap pengguna
    customer_name TEXT NOT NULL,
    product TEXT NOT NULL,
    qty NUMERIC NOT NULL,
    revenue NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- PENTING JIKA TABEL SUDAH PERNAH DIBUAT SEBELUMNYA:
-- Jalankan perintah ALTER ini satu per satu di SQL Editor jika tabel materials dan sales sudah ada:
-- ALTER TABLE public.materials ADD COLUMN user_id UUID REFERENCES auth.users(id);
-- ALTER TABLE public.sales ADD COLUMN user_id UUID REFERENCES auth.users(id);

-- Mengatur Row Level Security (RLS) jika dibutuhkan
-- Jika aplikasi ini hanya diakses lewat API backend Vercel secara server-side, 
-- kita tidak wajib mengaktifkan RLS karena request dikirim dari backend server tepercaya.
-- Namun demi keamanan opsional:
-- ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- =========================================================================
-- PERBARUAN: Dasbor Admin & Feedback
-- =========================================================================

-- 3. Membuat tabel 'profiles' untuk mencatat daftar pengguna
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id),
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Trigger untuk menambahkan user otomatis ke tabel profiles saat pendaftaran baru
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email)
  VALUES (new.id, new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Menghapus trigger lama jika ada agar tidak bentrok
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- Memasang trigger pada auth.users
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Jika sudah ada user terdaftar sebelumnya, jalankan perintah ini 1x secara manual di SQL Editor:
-- INSERT INTO public.profiles (id, email) SELECT id, email FROM auth.users ON CONFLICT DO NOTHING;

-- 4. Membuat tabel 'feedback' untuk menyimpan pesan dari user
CREATE TABLE IF NOT EXISTS public.feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
