-- Skema Tabel untuk PostgreSQL di Supabase

-- 1. Membuat tabel 'materials' untuk Pengadaan Bahan Baku (MM)
CREATE TABLE IF NOT EXISTS public.materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    qty NUMERIC NOT NULL,
    entry_date DATE NOT NULL,
    exp_date DATE NOT NULL,
    cost NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Membuat tabel 'sales' untuk Pesanan Penjualan (SD)
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT NOT NULL,
    product TEXT NOT NULL,
    qty NUMERIC NOT NULL,
    revenue NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Mengatur Row Level Security (RLS) jika dibutuhkan
-- Jika aplikasi ini hanya diakses lewat API backend Vercel secara server-side, 
-- kita tidak wajib mengaktifkan RLS karena request dikirim dari backend server tepercaya.
-- Namun demi keamanan opsional:
-- ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
